[build]
builder = "nixpacks"
buildCommand = "cp backend/prisma/schema.production.prisma backend/prisma/schema.prisma && cd backend && bun install && bun run build && bunx prisma generate && bunx prisma migrate deploy"

[deploy]
startCommand = "cd backend && bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
